version: '3'

x-airflow-common:
  &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: 'fb2mOYlebZUQfN7jPlM1zRXL0YhxNJZuQJ9XgT3hzuQ='
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'false'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__DAG_DEFAULT_VIEW: 'grid'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
  volumes:
    - ./dags:/opt/airflow/dags
    - ./app:/opt/airflow/app
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres

services:
  postgres:
      image: postgres:10.5
      restart: always
      environment:
        - POSTGRES_USER=airflow
        - POSTGRES_PASSWORD=airflow
      ports:
        - '5432:5432'
      volumes:
        - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - airflow-init

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    restart: always
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always
    depends_on:
      - airflow-init

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com && \
        airflow connections add 'fs_default' \
          --conn-type 'fs' \
          --conn-extra '{"path": "/"}' && \
        exit 0
    restart: on-failure

volumes:
  postgres-db-volume: